### ISSUE TITLE
Aren't those implemented tests rather integration tests than unit tests?

### ISSUE THREAD

**Issue by olivermack** [arangodb/arangodb-php#171]
Hey,

those tests implemented yet are quite extensive and have many dependencies in one tested logical unit. The `GraphBasicTest` for example does neither test the `Graph` class, nor the `GraphHandler` class directly; instead it addresses an integration of both of them. The `GraphExtendedTest` does so, too.

So, I'm asking myself if it would be nice to differ between unit and integration tests (or: to implement unit tests which follow some more of those _best practices_ known).

What do you think? Any opinions on that?

Cheers

**Comment by frankmayer** [comment]
Closing this, as an implementation of real unit tests with the current state of the driver seems difficult.
If there should be any changes to the state of the driver we may re-open this.

As for the   [ArangoDB-PHP-Core](https://github.com/frankmayer/ArangoDB-PHP-Core) driver, there was no time to develop it further, but there might be some time now.
