### ISSUE TITLE
Affected docs count method

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb-php#179]
Today I came across this and I think it should be somehow included in the SDK.

````php
$result = $stmt->execute()->getMetadata();
return (isset($result['extra'][Cursor::ENTRY_STATS]['writesExecuted'])) ?
           $result['extra'][Cursor::ENTRY_STATS]['writesExecuted'] : 0;
````
Thank you!

**Comment by frankmayer** [comment]
Just do be on the same page, are you, with "somehow", proposing to introduce a getExtra() method, or want to make sure that a key/value pair is always present? 
If it's the second, it should probably not be handled on the client side, but be made sure that it is included from the server side.

**Comment by razvanphp** [comment]
I would like more something like
````php
$count = $stmt->execute()->getAffectedRows();
````
but your idea is also good :+1:

**Comment by frankmayer** [comment]
I think you have a point here. :+1:  How about both?

```$extra = $stmt->execute()->getExtra();```
 for a direct access to the extras 

and something like 

```$writesExecuted = $stmt->execute()->getWritesExecuted();```
or
```$affectedDocs = $stmt->execute()->getAffectedDocs();```

for a chainabled an more direct access to this more widely used value.

BTW, I purposely left out "getAffectedRows" as we're not dealing with *rows* :smile:

**Comment by razvanphp** [comment]
Haha, true, sorry, strong mysql background here, I updated the title.

**Comment by frankmayer** [comment]
...yes, me too... no worries :smile:

**Comment by jsteemann** [comment]
I implemented the following methods in the 2.5 and devel branches of the driver:

- Cursor::getExtra()
- Cursor::getWarnings()
- Cursor::getWritesExecuted()
- Cursor::getWritesIgnored()
- Cursor::getScannedFull()
- Cursor::getScannedIndex()
- Cursor::getFiltered()

I also created a v2.5.1 tag which contains the changes.

**Comment by frankmayer** [comment]
Nicely done, Jan. As always. I would have done it over the weekend, but you were faster ;)
I'm slowly getting back into it again, though, and will be contributing again, so you can keep your focus on the DB.

**Comment by jsteemann** [comment]
Thanks.

**Comment by razvanphp** [comment]
Wow, that was fast, I already implemented it, looks great now.

Thank you!
