### ISSUE TITLE
Bad serialization for empty example

### ISSUE THREAD

**Issue by sandermarechal** [arangodb/arangodb-php#185]
Empty examples are wrongly serialized to `[]` instead of `{}`. For example, in `CollectionHandler->removeByExample()`, if you pass an empty `array()` as the example document.

**Comment by jsteemann** [comment]
Should be fixed in the 2.7 and devel branches of the driver, and tag v2.7.1.
Can you check if this fixes problem for you?

**Comment by sandermarechal** [comment]
Works fine now, thank you!
