### ISSUE TITLE
SSL port ignored by the SDK

### ISSUE THREAD

**Issue by razvanphp** [arangodb/arangodb-php#186]
You can see in [HttpHelper class](https://github.com/arangodb/arangodb-php/blob/master/lib/triagens/ArangoDb/HttpHelper.php#L254), the `ConnectionOptions::OPTION_PORT` is still used, even tho it's deprecated, and the port should be part of the endpoint. For SSL it seems you cannot specify it twice.

To be able to connect to an SSL endpoint, I had te replace the second argument of `fsockopen` with `-1`, and specify the port only in the `ConnectionOptions::OPTION_ENDPOINT`. I don't know if this breaks some other connection types tho...

**Comment by jsteemann** [comment]
Fixed in 2.8 and devel branches.
For the 2.8 branch I have created a tag `v2.8.1` that contains the modification.
