### ISSUE TITLE
Using _sanitize and _hiddenAttributes options in CollectionHandler->all() don't seem to work

### ISSUE THREAD

**Issue by ingipingi** [arangodb/arangodb-php#194]
Here is an example of my code
```php
$accounts = $collectionHandler->all('Accounts', [
	'_sanitize' => true,
	'_hiddenAttributes' => ['password']
]);
```

If I understand correctly this should hide the password, _id and _rev attributes. But it doesn't.

It works fine using setHiddenAttributes() on Documents

I'm using 3.0 version of arrangodb-php, version 3.0.6 of arangodb server on Ubuntu Server 16.04

**Comment by frankmayer** [comment]
Hi @ingipingi ,
could you checkout the devel branch and try it again? It should work now.

**Comment by frankmayer** [comment]
The expected functionality was restored with v3.0.7. However we're on v3.0.8  now.
And the newest pushes to the main branches (devel, master & 3.0) have updated docs, too.
