### ISSUE TITLE
unclear how to use the transaction method

### ISSUE THREAD

**Issue by alexblattner** [arangodb/arangodb-php#201]
Fatal error: Uncaught triagens\ArangoDb\ServerException: 10 missing/invalid action definition for transaction - Uncaught SyntaxError: Unexpected token ; - SyntaxError: Unexpected token ; at post_api_transaction (c:\Program Files\ArangoDB 3\share\arangodb3\js\actions\api-transaction.js:49:16) at Function.actions.defineHttp.callback (c:\Program Files\ArangoDB 3\share\arangodb3\js\actions\api-transaction.js:66:11) thrown in C:\xampp\htdocs\"project name"\arangodb\lib\triagens\ArangoDb\Connection.php on line 522

what may be the problem? could examples be provided?

**Comment by jsteemann** [comment]
Can you provide the calling PHP code? That will help debugging and answering this question. Thanks!

**Comment by alexblattner** [comment]
I apologize.... I forgot to put "triagens\ArangoDb\".... everything works fine

**Comment by jsteemann** [comment]
No worries and thanks for the confirmation. I'll close the issue then.
