### ISSUE TITLE
how to get response in standard json - shortest path(PHP)

### ISSUE THREAD

**Issue by fothismanrequest** [arangodb/arangodb-php#225]
**the blow code give me an non-standard output(json encoder can't  encode it to json)**

namespace triagens\ArangoDb;
require 'dependencies/arangophp/vendor/autoload.php'; 
$connectionOptions =array(
    ConnectionOptions::OPTION_ENDPOINT => 'tcp://x.x.x.x',
    ConnectionOptions::OPTION_AUTH_TYPE => 'Basic',
    ConnectionOptions::OPTION_AUTH_USER => 'root',
    ConnectionOptions::OPTION_AUTH_PASSWD => 'xxxxx',
    ConnectionOptions::OPTION_CONNECTION => 'Close',
    ConnectionOptions::OPTION_TIMEOUT => 3,
    ConnectionOptions::OPTION_DATABASE => 'Conversation',
    ConnectionOptions::OPTION_RECONNECT => true,
    ConnectionOptions::OPTION_CREATE => true,
    ConnectionOptions::OPTION_UPDATE_POLICY => UpdatePolicy::LAST,
);
 

$connection = new Connection($connectionOptions);
$statement = new Statement($connection, array("query" => "FOR v, e IN OUTBOUND SHORTEST_PATH 'Person/9380404077' TO 'Person/yyy' GRAPH 'ConversationGraph' RETURN [e]"));
$cursor = $statement->execute();
$x=$cursor->getAll();
print_r ($x);

how i can get response in json format ?

**Comment by jsteemann** [comment]
I am not 100% sure what the desired output is.
The `$cursor->getAll()` call will mostly likely return an array with objects of type `Document`. If you `print_r` that, it will print some PHP representation of the data but no JSON representation.

What you can do is loop over the cursor result and print each individual result value as JSON, e.g.
```php
foreach ($cursor->getAll() as $value) {
  if ($value instanceof Document) {
    print $value->toJson() . PHP_EOL;
  } else {
    print json_encode($value) . PHP_EOL;
  }
}
```

**Comment by frankmayer** [comment]
If you need the JSON response without going throught the documents, you have to include the '_flat' option. See https://github.com/arangodb/arangodb-php/blob/devel/README.md#running-an-aql-query

Closing this issue now. Feel free to reopen it if necessary.
