### ISSUE TITLE
Date for next release 3.2?

### ISSUE THREAD

**Issue by sandrokeil** [arangodb/arangodb-php#230]
I'm looking forward for a new release with the new namespace `ArangoDBClient` and the new Composer name `arangodb/arangodb` for packagist.org. Any plans for this?

**Comment by jsteemann** [comment]
Seems that though we had a 3.2 branch, we did not have a v3.2 tag. I have now created and pushed one.
Can you eventually check if it's usable and actually contains the requested changes? 
Thanks!

**Comment by sandrokeil** [comment]
`composer require triagens/arangodb:^3.2` works but `composer require arangodb/arangodb:^3.2` works not. I don't know if you want to change the Composer name too. It's ok for me and I can now rely on the new stable version. Thanks.
