### ISSUE TITLE
Missing optional body param for delete request to remove multiple documents

### ISSUE THREAD

**Issue by sandrokeil** [arangodb/arangodb-php#233]
The method [\ArangoDBClient\Connection::delete](https://github.com/arangodb/arangodb-php/blob/devel/lib/ArangoDBClient/Connection.php#L295) needs an optional body param to [remove multiple documents](https://docs.arangodb.com/3.3/HTTP/Document/WorkingWithDocuments.html#removes-multiple-documents).

To avoid a BC break, I recommend to add it as a third optional argument. What do you think?

**Comment by jsteemann** [comment]
Sounds good!

**Comment by sandrokeil** [comment]
@jsteemann Can you create a new release with this feature/fix please?

**Comment by jsteemann** [comment]
You mean a 3.3 release? I then have to backport things to the 3.3 branch, and also appy the TravisCI changes in that branch.

**Comment by jsteemann** [comment]
Ok, there is now release v3.3.0.
