### ISSUE TITLE
SORT functionality without AQL

### ISSUE THREAD

**Issue by Ashafaat** [arangodb/arangodb-php#246]
it's necessary to have sort ability when we use **getByExample()** [collectionHandler object] and other  type of functions that return array of documents.
there is LIMIT functionality but SORT is needed as i see. for now this is just possible with AQL queries.

**Comment by dothebart** [comment]
Please note that the corrosponding simple queries are deprecated - see https://docs.arangodb.com/3.3/Manual/Appendix/Deprecated/SimpleQueries/ - so this will rather go away completely than being extended. 

The current implementation translates the data you give it into AQL - which may also fail to be as smart as needed. 

If you need more than a document that you have the `_key` of, you should rather use AQL to get your required documents.

**Comment by Ashafaat** [comment]
thank you for lighting me up!
It was very helpful.
