### ISSUE TITLE
ArangoDB <=> swoole

### ISSUE THREAD

**Issue by flddr** [arangodb/arangodb-php#254]
Hi,

i am new to ArangoDB - it looks very interesting.

While new to _swoole_, too, i would like to know more about using it together.

Is there some stuff about?

:) thank you for help

**Comment by jsteemann** [comment]
The ArangoDB PHP driver has no Swoole integration.
It makes blocking (i.e. sync) HTTP calls to the ArangoDB database server backend however, so I am not sure if that will be a perfect match for something that's concurrency- and coroutine-based.
Anyway, I have no experience at all with Swoole so I can't really help further with this. Maybe there are others that can help or share their opinion.
Please feel free to ask others in ArangoDB's community Slack at slack.arangodb.com if you haven't tried already.

**Comment by flddr** [comment]
@jsteemann thank you very much for this response :+1:
