### ISSUE TITLE
ArangoDB 3.4 support?

### ISSUE THREAD

**Issue by sandermarechal** [arangodb/arangodb-php#258]
When can I expect a release with support for ArangoDB 3.4? Currently there doesn't even appear to be a 3.4 branch.

**Comment by jsteemann** [comment]
@sandermarechal : we actually started working on it. Latest changes are in the devel branch, but view support is still lacking. When view support has been added, there will be a 3.4 branch.

**Comment by sandermarechal** [comment]
Thanks. Is the master branch already up-to-date with the rest of ArangoDB 3.4? I mean, does it work without the view stuff?

**Comment by jsteemann** [comment]
The master branch is still on the state of 3.3 affairs, as by our convention the master branch contains the same state as the latest stable release branch, which currently is 3.3 for the driver.
However, I have now created a 3.4 branch in the driver repository. This should already work when connecting to a 3.4 server instance, but it still lacks support for views.

**Comment by sleto-it** [comment]
Hi - 

Basic support for arangosearch views was added in the driver version 3.4.0, via the View and ViewHandler classes.

Driver 3.4.0 has been published - changelog https://github.com/arangodb/arangodb-php/blob/3.4/CHANGELOG.md

Release announcement: https://groups.google.com/forum/#!topic/arangodb-announce/v8D8j88-M-A

Please let us know if there are additional questions or we can consider this resolved

Thanks,

**Comment by sandermarechal** [comment]
That's great, thanks!
