### ISSUE TITLE
ConnectionOptions::OPTION_TIMEOUT is also used for the response

### ISSUE THREAD

**Issue by gghdev** [arangodb/arangodb-php#281]
Hi there,

At the moment, the same timeout option, ``ConnectionOptions::OPTION_TIMEOUT``, is used both when establishing the socket (as expected) and for ``stream_set_timeout()`` in ``HttpHelper::createConnection()``.

Ideally I'd set the former to something short, like 3 seconds, and the latter to something longer, like 10 seconds in order to account for longer-running queries. Currently, I need to set the higher value for both.

Should there be an additional option along the lines of ``ConnectionOptions::OPTION_READ_TIMEOUT``?

**Comment by jsteemann** [comment]
@gghdev : I have created a PR https://github.com/arangodb/arangodb-php/pull/283 to address this issue.
Do you mind checking if that PR solves your problem? 
Thanks!

**Comment by gghdev** [comment]
@jsteemann Looks perfect -- I've tested your commit in my project and it seems to be working as expected. Thanks Jan!

**Comment by jsteemann** [comment]
Fixed via above PR in `devel` and `3.8` branches.

**Comment by gghdev** [comment]
@jsteemann, when do you reckon we'll see a 3.8.0 release, roughly?

**Comment by jsteemann** [comment]
@gghdev : I think the driver is ready for 3.8 now, and ArangoDB 3.8 is also going to be GAed soon. So I guess next week it's time for tagging!

**Comment by gghdev** [comment]
@jsteemann Ah, cool, good stuff!

**Comment by jsteemann** [comment]
Made available via tag `v3.8.0` a few weeks ago.
