### ISSUE TITLE
HttpHelper::transfer() / PHP 8 /  stripos(): Argument #3 ($offset) must be contained in argument #1 ($haystack)

### ISSUE THREAD

**Issue by gghdev** [arangodb/arangodb-php#282]
Hi,

An extra check is needed to avoid a fatal error in PHP 8 in relation to ``stripos()`` -- specifically the call in ``HttpHelper::transfer()`` which uses an offset of 12. If for whatever reason the haystack is less than 12 characters long, PHP 8 throws:

 ``Uncaught ValueError: stripos(): Argument #3 ($offset) must be contained in argument #1 ($haystack) in /var/www/vendor/triagens/arangodb/lib/ArangoDBClient/HttpHelper.php on line 258``

I've only seen this error once, after many requests on the same connection, and I'm not sure if there's another issue at play or whether a simple check of the string length is sufficient to resolve the issue?

**Comment by jsteemann** [comment]
@gghdev : The particular issue should be fixed by https://github.com/arangodb/arangodb-php/pull/285
There may be more such issues lurking which don't cause trouble with PHP versions < 8.
I haven't prepared the CI for PHP 8 tests yet, but this will happen at some point.

**Comment by gghdev** [comment]
@jsteemann Sounds good. Thanks for making this tweak.

**Comment by jsteemann** [comment]
Fixed via the above PR in `devel` and `3.8` branches.

**Comment by jsteemann** [comment]
Made available via tag `v3.8.0` a few weeks ago.
