### ISSUE TITLE
Deprecation Warnings with PHP 8.2

### ISSUE THREAD

**Issue by fwtag-tnm** [arangodb/arangodb-php#305]
Hi there, 

is this bundle still under maintenance? 

It would be great if you could do the necessary steps for the compatibility to PHP 8.2 since execution under 8.2 fires a lot of deprecation warnings in the logs. 

Thank you!
Frank

**Comment by dothebart** [comment]
Hi, 
I will close this as duplicate to https://github.com/arangodb/arangodb-php/issues/304 which also contains a link to another still maintained PHP driver.

**Comment by fwtag-tnm** [comment]
So is this bundle not maintained anymore? Please leave a deprecation note at the bundle's description.
